version: "3.7"
services:
  nginx:
    container_name: lmm-gateway-nginx
    image: nginx:1.14.1-alpine
    volumes:
      - ./nginx/log:/var/log/nginx
      - ./nginx/conf:/etc/nginx/conf
      - ./nginx/upstream:/etc/nginx/upstream
      - ./nginx/modules/:/etc/nginx/modules
      - ./nginx/ssl/:/etc/nginx/ssl
      - ./nginx/allowedips/:/etc/nginx/allowedips
    environment:
      TZ: Asia/Tokyo
