version: "3.7"
services:
  nginx:
    image: nginx:1.14.1-alpine
    restart: on-failure
    volumes:
      - ./nginx/run:/var/run
      - ./nginx/log:/var/log/nginx
      - ./nginx/conf:/etc/nginx/conf
      - ./nginx/upstream:/etc/nginx/upstream
      - ./nginx/modules/:/etc/nginx/modules
      - ./nginx/ssl/:/etc/nginx/ssl
      - ./nginx/allowedips/:/etc/nginx/allowedips
    environment:
      TZ: Asia/Tokyo
    ports:
      - 80:80
      - 443:443
    networks:
      - lmm

networks:
  lmm:
    name: lmm
