version: "3.7"
services:
  nginx:
    container_name: lmm_gateway_nginx
    image: nginx:1.14
    restart: always
    volumes:
      - ./nginx/log:/var/log/nginx
      - ./nginx/conf:/etc/nginx/conf
      - ./nginx/ssl:/etc/nginx/ssl
      - ./nginx/modules/:/etc/nginx/modules
    environment:
      TZ: Asia/Tokyo
    networks:
      - lmm
    ports:
      - 80:80
      - 443:443

networks:
  lmm:
    name: lmm
