version: "3.7"
services:
  nginx:
    container_name: lmm-gateway-nginx
    image: nginx:1.14
    volumes:
      - ./nginx/log:/var/log/nginx
      - ./nginx/conf:/etc/nginx/conf
      - ./nginx/modules/:/etc/nginx/modules
      - ./nginx/allowedips/:/etc/nginx/allowedips
    environment:
      TZ: Asia/Tokyo
    network_mode: host
