version: "3.7"
services:
  manager:
    container_name: manager
    image: node:9.9
    volumes:
      - .:/manager
    command: npm --prefix /manager run build && npm --prefix /manager start
    environment:
      TZ: Asia/Tokyo
    networks:
      - manager
    ports:
      - 8004:8004

networks:
  manager:
    name: manager
