version: "3"
services:
  manager:
    command: npm --prefix /manager run dev
    environment:
      SERVER_HOST: '0.0.0.0'
      SERVER_PORT: 8004
      API_URL: 'http://host.docker.internal:8002'
      API_URL_BROWSER: 'http://api.lmm.local'
      ASSET_URL: 'http://asset.lmm.local'
