version: "3.7"
services:
  manager:
    command: npm --prefix /manager run dev
    environment:
      SERVER_HOST: '0.0.0.0'
      SERVER_PORT: 8004
      API_URL: 'https://api.lmm.local'
      API_URL_BROWSER: 'https://api.lmm.local'
      ASSET_URL: 'https://asset.lmm.local'
    networks:
      - lmm

networks:
  lmm:
    external:
      name: lmm
