version: "3.7"
services:
  manager:
    image: node:lts-alpine
    volumes:
      - .:/manager
    environment:
      TZ: Asia/Tokyo
    networks:
      - lmm

networks:
  lmm:
    external:
      name: lmm
