version: "3.7"

services:
  zookeeper:
    container_name: lmm-logging-zookeeper
    image: zookeeper:3.4.13
  kafka:
    container_name: lmm-logging-kafka
    image: wurstmeister/kafka:2.12-2.1.0
    ports:
      - 9092:9092
    links:
      - zookeeper
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
