version: "3.7"

services:
  pubsub:
    image: golang:1.12.0
    volumes:
      - ./go:/go
      - ./../cloud/gcp/credentials/service_account.json:/gcp/credentials/service_account.json
    working_dir: /go/src/lmm/logging
    environment:
      TZ: Asia/Tokyo
      GO111MODULE: 'on'
    command: pubsub
    networks:
      - lmm

networks:
  lmm:
    external:
      name: lmm
