version: 2.1

jobs:
  api:
    docker:
      - image: circleci/golang:1.12.0
      - image: circleci/mysql:5.7.25
    environment:
      MYSQL_HOST: localhost
      MYSQL_PORT: 3306
      MYSQL_NAME: lmm_test
      MYSQL_USER: root
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
      HTTP_TIMEOUT_SECOND: 3

    steps:
      - checkout
      - restore_cache:
          keys:
            - &api_go_mod_cache_key api_go_mod-v1-{{ checksum "api/go/src/lmm/api/go.mod" }}-{{ checksum "api/go/src/lmm/api/go.sum" }}
            - api_go_mod-v1-{{ checksum "api/go/src/lmm/api/go.mod" }}-
            - api_go_mod-v1-
          paths:
            - &api_go_mod_cache_path /go/pkg/mod
      - run:
          name: go mod download
          command: |
            cd api/go/src/lmm/api
            go mod download
      - save_cache:
          key:
            - *api_go_mod_cache_key
          paths:
            - *api_go_mod_cache_path
      - run:
          name: Setup API MySQL
          command: |
            dockerize -wait tcp://127.0.0.1:3306 -timeout 120s
            sudo apt install -y mysql-client || true
            cat api/mysql/sql/init_test.sql | mysql -h localhost --protocol TCP -uroot
      - run:
          name: API Go Test
          command: |
            export LMM_API_TOKEN_KEY=$(cat /proc/sys/kernel/random/uuid | sed 's/-//g')
            cd api/go/src/lmm/api
            go test ./... -count 1 -cover -v

workflows:
  version: 2.1
  test:
    jobs:
      - api
