version: 2
jobs:
  build:
    machine:
      image: circleci/classic:edge
    steps:
      - checkout
      - restore_cache:
          key: go-mod-{{ checksum "api/go.mod" }}
      - run:
          name: Test API
          command: |
            cd api
            mkdir -p .env
            chmod -R 777 mysql
            echo LMM_API_TOKEN_KEY=$(uuidgen | sed -e 's/-//g') > .env/test.env
            pip install --upgrade pip
            pip install docker-compose
            make install
            make test
      - save_cache:
          key: go-mod-{{ checksum "api/go.mod" }}
          paths:
            - /go/pkg/mod
