version: 2.1

references:
  manager_master_branch: &manager_master_branch /^master\/manager$/
  manager_branches: &manager_branches /^manager\/.*/

jobs:
  api:
    docker:
      - image: circleci/golang:1.12.0
      - image: circleci/mysql:5.7.25
    environment:
      MYSQL_HOST: localhost
      MYSQL_PORT: 3306
      MYSQL_NAME: lmm_test
      MYSQL_USER: root
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
      HTTP_TIMEOUT_SECOND: 3

    steps:
      - checkout
      - restore_cache:
          keys:
            - &api_go_mod_cache_key api_go_mod-v1-{{ checksum "api/go/src/lmm/api/go.mod" }}-{{ checksum "api/go/src/lmm/api/go.sum" }}
            - api_go_mod-v1-{{ checksum "api/go/src/lmm/api/go.mod" }}-
            - api_go_mod-v1-
          paths:
            - &api_go_mod_cache_path /go/pkg/mod
      - run:
          name: go mod download
          command: |
            cd api/go/src/lmm/api
            go mod download
      - save_cache:
          key: *api_go_mod_cache_key
          paths:
            - *api_go_mod_cache_path
      - run:
          name: Setup API MySQL
          command: |
            dockerize -wait tcp://127.0.0.1:3306 -timeout 120s
            sudo apt install -y mysql-client || true
            cat api/mysql/sql/init_test.sql | mysql -h localhost --protocol TCP -uroot
      - run:
          name: API Go Test
          command: |
            export LMM_API_TOKEN_KEY=$(cat /proc/sys/kernel/random/uuid | sed 's/-//g')
            cd api/go/src/lmm/api
            go test ./... -count 1 -cover -v

  manager_build_and_deploy:
    docker:
      - image: google/cloud-sdk
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - restore_cache:
          keys:
            - &manager_node_modules_cache_key manager_node_modules-v1-{{ arch }}-{{ checksum "manager/package.json" }}
            - manager_node_modules-v1-{{ arch }}-
            - manager_node_modules-v1-
      - run:
          name: npm install
          command: |
            cd manager
            npm install
      - save_cache:
          key: *manager_node_modules_cache_key
          paths:
            - manager/node_modules
      - run:
          name: nuxt build
          command: |
            cd manager
            npm run build
      - run:
          name: deploy
          command: |
            echo "TODO"

workflows:
  version: 2.1
  test_build_deploy:
    jobs:
      - api:
          filters:
            branches:
              ignore:
                - *manager_branches
      - manager_build_and_deploy
