version: 2
jobs:
  build:
    machine:
      image: circleci/classic:edge
    steps:
      - checkout
      - restore_cache:
          key: api-go-mod-{{ arch }}-{{ .Branch }}-{{ checksum "api/go/src/lmm/api/go.mod" }}
      - restore_cache:
          key: api-mysql-{{ arch }}-{{ .Branch }}-{{ checksum "api/mysql/sql/init_test.sql" }}
      - run:
          name: Test API
          command: |
            cd api
            mkdir -p .env
            chmod -R 777 mysql
            echo LMM_API_TOKEN_KEY=$(uuidgen | sed -e 's/-//g') > .env/test.env
            pip install --upgrade pip
            pip install docker-compose
            make install
            make test
      - save_cache:
          key: api-go-mod-{{ arch }}-{{ .Branch }}-{{ checksum "api/go/src/lmm/api/go.mod" }}
          paths:
            - api/go/pkg/mod
      - save_cache:
          key: api-mysql-{{ arch }}-{{ .Branch }}-{{ checksum "api/mysql/sql/init_test.sql" }}
          paths:
            - api/mysql/lib
