version: 2
jobs:
  build:
    machine:
      image: circleci/classic:edge
    steps:
      - checkout
      - run:
          name: Build API
          command: |
            cd api
            make build
      - run:
          name: Test API
          command: |
            cd api
            mkdir -p .env
            chmod -R 777 mysql
            echo LMM_API_TOKEN_KEY=$(uuidgen | sed -e 's/-//g') > .env/test.env
            pip install --upgrade pip
            pip install docker-compose
            make install
            make test
      - run:
          name: Test API CLI
          command: |
            cd api
            make cli env=dev commands="hello-world"
