version: "3.7"
services:
  asset:
    container_name: lmm-asset
    image: golang:1.11
    working_dir: /go/src/lmm/asset
    volumes:
      - ./go/pkg:/go/pkg
      - ./go/src/lmm/asset:/go/src/lmm/asset
      - ./static/images:/static/images
      - ./static/photos:/static/photos
    command: go run main.go
    environment:
      TZ: Asia/Tokyo
      GO111MODULE: 'on'
    networks:
      - lmm
      - lmm-asset
    ports:
      - 8003:8003
  subscriber:
    container_name: lmm-asset-subscriber
    image: golang:1.11
    working_dir: /go/src/lmm/subscriber
    volumes:
      - ./go/pkg:/go/pkg
      - ./go/src/lmm/subscriber:/go/src/lmm/subscriber
      - ./static/images:/static/images
      - ./static/photos:/static/photos
    command: go run main.go
    environment:
      TZ: Asia/Tokyo
      GO111MODULE: 'on'
    networks:
      - lmm-asset

networks:
  lmm-asset:
    name: lmm-asset
  lmm:
    external:
      name: lmm
