version: "3"
services:
  asset:
    image: golang:1.11
    working_dir: /go/src/lmm/asset
    volumes:
      - ./go:/go
      - ./static:/static
    command: go run main.go
    environment:
      TZ: Asia/Tokyo
      GO111MODULE: 'on'
    ports:
      - 8003:8003
