version: "3.7"
services:
  asset:
    image: golang:1.12.0
    working_dir: /go/src/lmm/asset
    volumes:
      - ./go:/go
      - ./static/images:/static/images
      - ./static/photos:/static/photos
    command: asset
    environment:
      TZ: Asia/Tokyo
      GO111MODULE: 'on'
    networks:
      - lmm

networks:
  lmm:
    external:
      name: lmm
