version: "3.7"
services:
  asset:
    image: golang:1.11.5-alpine3.9
    working_dir: /go/src/lmm/asset
    volumes:
      - ./go:/go
      - ./static/images:/static/images
      - ./static/photos:/static/photos
    command: asset
    environment:
      TZ: Asia/Tokyo
      GO111MODULE: 'on'
      CGO_ENABLED: 0
    networks:
      - lmm
  subscriber:
    image: golang:1.11.5-alpine3.9
    working_dir: /go/src/lmm/asset
    volumes:
      - ./go/:/go/
      - ./static/images:/static/images
      - ./static/photos:/static/photos
    command: subscriber
    environment:
      TZ: Asia/Tokyo
      GO111MODULE: 'on'
      CGO_ENABLED: 0
    networks:
      - lmm

networks:
  lmm:
    external:
      name: lmm
