version: "3"
services:
  docs:
    image: swaggerapi/swagger-ui
    volumes:
      - ../docs/api:/usr/share/nginx/html/api
    environment:
      API_URL: api/index.yaml
    ports:
      - "8084:8080"
