version: "3"
services:
  api:
    image: golang:1.9
    volumes:
      - ../api:/go/src/lmm/api
      - ../api/dep:/go/src
    command: go run /go/src/lmm/api/main.go
    environment:
      TZ: Asia/Tokyo
    depends_on:
      - mysql
    links:
      - mysql:lmm-mysql
  cli:
    image: lmm/cli
    build:
      context: ../script
      dockerfile: ../docker/cli/Dockerfile
    volumes:
      - ../script:/script
    environment:
      TZ: Asia/Tokyo
    depends_on:
      - mysql
    links:
      - mysql:lmm-mysql
  docs:
    image: swaggerapi/swagger-ui:v3.14.2
    volumes:
      - ../docs/api:/usr/share/nginx/html/api
    environment:
      API_URL: api/index.yaml
  mysql:
    image: mysql:5.7
    volumes:
      - ./mysql/lib:/var/lib/mysql
      - ./mysql/log:/var/log/mysql
      - ./mysql/my.cnf:/etc/mysql/my.cnf
    environment:
      TZ: Asia/Tokyo
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
    ports:
      - "3306:3306"
  nginx:
    image: nginx:1.14
    restart: always
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/log:/var/log/nginx
      - ./nginx/conf:/etc/nginx/conf
      - ./nginx/modules/:/etc/nginx/modules
    environment:
      TZ: Asia/Tokyo
    ports:
      - "80:80"
    depends_on:
      - api
      - docs
    links:
      - api:lmm-api
      - docs:lmm-docs
