version: "3"
services:
  docs:
    image: swaggerapi/swagger-ui
    volumes:
      - ../docs/api:/usr/share/nginx/html/api
    environment:
      API_URL: api/index.yaml
  mysql:
    image: mysql:5.7.22
    volumes:
      - ./mysql/lib:/var/lib/mysql
      - ./mysql/log:/var/log/mysql
      - ./mysql/my.cnf:/etc/mysql/my.cnf
    environment:
      TZ: Asia/Tokyo
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
    ports:
      - "3306:3306"
  nginx:
    image: nginx:1.14
    restart: always
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/log:/var/log/nginx
      - ./nginx/conf:/etc/nginx/conf
      - ./nginx/modules/:/etc/nginx/modules
    environment:
      TZ: Asia/Tokyo
    ports:
      - "80:80"
    depends_on:
      - docs
    links:
      - docs:lmm-docs
