version: "3"
services:
  api:
    env_file:
      - ./api/.dev.env
    environment:
      DB_HOST: lmm-mysql
      DB_PORT: 3306
      DB_NAME: lmm
      DB_USER: root
      HTTP_TIMEOUT_SECOND: 3
  app:
    command: npm --prefix /app run dev
  manager:
    command: npm --prefix /manager run dev
  nginx:
    volumes:
      - ./nginx/nginx.dev.conf:/etc/nginx/nginx.conf
