version: "3"
services:
  api:
    image: lmm/api
    build:
      context: ../api
      dockerfile: ../docker/api/Dockerfile
    volumes:
      - ../api:/go/src/lmm/api
      - ../static:/static
    working_dir: /go/src/lmm/api
    command: go run cmd/api/main.go
    env_file:
      - ./api/.env
    environment:
      TZ: Asia/Tokyo
      GO111MODULE: 'on'
      HTTP_TIMEOUT_SECOND: 10
    depends_on:
      - mysql
    links:
      - mysql:lmm-mysql
      - redis:lmm-redis
  app:
    image: node:9.9
    volumes:
      - ../app:/app
    command: npm --prefix /app start
    environment:
      TZ: Asia/Tokyo
  cli:
    image: lmm/cli
    build:
      context: ../script
      dockerfile: ../docker/cli/Dockerfile
    volumes:
      - ../script:/script
    working_dir: /script
    environment:
      TZ: Asia/Tokyo
    depends_on:
      - mysql
    links:
      - mysql:lmm-mysql
  docs:
    image: swaggerapi/swagger-ui:v3.14.2
    volumes:
      - ../docs/api:/usr/share/nginx/html/api
    environment:
      API_URL: api/index.yml
  static:
    image: golang:1.11
    volumes:
      - ../static/src:/go/src/lmm/static
    command: go run /go/src/lmm/static/main.go
    environment:
      TZ: Asia/Tokyo
  manager:
    image: node:9.9
    volumes:
      - ../manager:/manager
    command: npm --prefix /manager start
    environment:
      TZ: Asia/Tokyo
  mysql:
    image: mysql:5.7
    volumes:
      - ./mysql/lib:/var/lib/mysql
      - ./mysql/log:/var/log/mysql
      - ./mysql/my.cnf:/etc/mysql/my.cnf
    environment:
      TZ: Asia/Tokyo
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
    ports:
      - "3306:3306"
  redis:
    image: redis:5.0-rc
    ports:
      - "6379:6379"
  nginx:
    image: nginx:1.14
    restart: always
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/log:/var/log/nginx
      - ./nginx/conf:/etc/nginx/conf
      - ./nginx/modules/:/etc/nginx/modules
      - ../static/images:/static/images
    environment:
      TZ: Asia/Tokyo
    ports:
      - "80:80"
    depends_on:
      - api
      - app
      - docs
      - manager
      - static
    links:
      - api:lmm-api
      - app:lmm-app
      - docs:lmm-docs
      - manager:lmm-manager
      - static:lmm-static
