version: "3"
services:
  docs:
    image: swaggerapi/swagger-ui
    volumes:
      - ../docs/api:/usr/share/nginx/html/api
    environment:
      API_URL: api/index.yaml
  nginx:
    image: nginx:1.14
    restart: always
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/log:/var/log/nginx
      - ./nginx/conf:/etc/nginx/conf
      - ./nginx/modules/:/etc/nginx/modules
    environment:
      TZ: Asia/Tokyo
    ports:
      - "80:80"
    depends_on:
      - docs
    links:
      - docs:lmm-docs
