version: "3"
services:
  api:
    env_file:
      - ./api/.test.env
    environment:
      DATABASE_NAME: lmm_test
      HTTP_TIMEOUT_SECOND: 1
    working_dir: /go/src/lmm/api
    command: bash
  app:
    command: echo "not implemented"
  static:
    command: echo "not implemented"
  manager:
    command: echo "not implemented"
