runtime: nodejs10
env: standard
instance_class: F2

handlers:
  - url: /_nuxt
    static_dir: .nuxt/dist/client
    secure: always

  - url: /(.*\.(gif|png|jpg|ico|txt))$
    static_files: static/\1
    upload: static/.*\.(gif|png|jpg|ico|txt)$
    secure: always

  - url: /.*
    script: auto
    secure: always

env_variables:
  API_URL: https://api.lumingming.net
  API_URL_BROWSER: https://api.lumingming.net
  ASSET_URL: https://asset.lumingming.net
  NODE_ENV: production
  TZ: Asia/Tokyo
