version: "3.7"
services:
  app:
    image: node:10.15.1-alpine
    volumes:
      - .:/app
    environment:
      TZ: Asia/Tokyo
    networks:
      - lmm

networks:
  lmm:
    external:
      name: lmm
