version: "3.7"
services:
  app:
    container_name: lmm_app
    image: node:9.9
    volumes:
      - .:/app
    working_dir: /app
    command: npm --prefix /app run build && npm --prefix /app start
    environment:
      TZ: Asia/Tokyo
    networks:
      - lmm
    ports:
      - 8001:8001

networks:
  lmm:
    external:
      name: lmm
