version: "3.7"
services:
  app:
    container_name: lmm-app
    image: node:lts-alpine
    volumes:
      - .:/app
    environment:
      TZ: Asia/Tokyo
    networks:
      - lmm

networks:
  lmm:
    external:
      name: lmm
