version: "3.7"
services:
  app:
    command: npm --prefix /app start
    environment:
      TZ: Asia/Tokyo
      HOST: '0.0.0.0'
      PORT: 8001
      API_URL: https://api.lumingming.net
      API_URL_BROWSER: https://api.lumingming.net
      ASSET_URL: https://asset.lumingming.net
    restart: always
