version: 1
update_configs:
  - package_manager: "go:modules"
    directory: "/api/go/src/lmm/api"
    update_schedule: "monthly"
  - package_manager: "javascript"
    directory: "/app"
    update_schedule: "monthly"
  - package_manager: "javascript"
    directory: "/manager"
    update_schedule: "monthly"
