openapi: 3.0.0

servers:
  - url: https://api.lmm.im

paths:
  /v1/signup:
    $ref: ./paths/v1_signup.yaml
  /v1/signin:
    $ref: ./paths/v1_signin.yaml

tags:
  - name: signup
    description: 注册账号
  - name: signin
    description: 登陆账号
  - name: verify
    description: 验证账号
  - name: blog
    description: 博客
  - name: image
    description: 图片
