version: "3.7"
services:
  docs:
    image: swaggerapi/swagger-ui:v3.14.2
    volumes:
      - ./api:/usr/share/nginx/html/api
    environment:
      API_URL: api/index.yml
    networks:
      - doc
    ports:
      - 8005:8080

networks:
  doc:
    name: doc
