version: "3"
services:
  api:
    env_file:
      - ./.env/test.env
    volumes:
      - ./sql/init_test.sql:/docker-entrypoint-initdb.d/init_test.sql
    environment:
      DB_HOST: api-mysql
      DB_PORT: 3306
      DB_NAME: lmm_test
      DB_USER: root
      HTTP_TIMEOUT_SECOND: 1
    working_dir: /go/src/lmm/api
    command: bash
