version: "3"
services:
  api:
    env_file:
      - ./api/.test.env
    environment:
      DB_HOST: lmm-mysql
      DB_PORT: 3306
      DB_NAME: lmm_test
      DB_USER: root
      HTTP_TIMEOUT_SECOND: 1
    working_dir: /go/src/lmm/api
    command: bash
  app:
    command: echo "not implemented"
  asset:
    command: echo "not implemented"
  manager:
    command: echo "not implemented"
