version: "3.7"
services:
  api:
    env_file:
      - ./.env/test.env
    environment:
      MYSQL_HOST: mysql
      MYSQL_PORT: 3306
      MYSQL_NAME: lmm_test
      MYSQL_USER: root
      REDIS_SERVER: redis:6379
      REDIS_CONN_TIMEOUT_SECOND: 3
      HTTP_TIMEOUT_SECOND: 1
    working_dir: /go/src/lmm/api
    command: bash -c "go test ./... -count 1 -cover -v"
  mysql:
    volumes:
      - ./mysql/sql/init_test.sql:/mysql/sql/init_test.sql
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
    command: --init-file /mysql/sql/init_test.sql
