version: "3.7"
services:
  api:
    env_file:
      - ./.env/dev.env
    environment:
      APP_HOST: https://www.lmm.local
      MYSQL_HOST: mysql
      MYSQL_PORT: 3306
      MYSQL_NAME: lmm
      MYSQL_USER: root
      RABBIT_HOST: rabbitmq
      RABBIT_PORT: 5672
      RABBIT_USER: guest
      RABBIT_PASS: guest
      HTTP_TIMEOUT_SECOND: 3
    networks:
      - lmm
      - lmm-api
  mysql:
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
    networks:
      - lmm-api
