version: "3.7"
services:
  api:
    build:
      context: .
      dockerfile: docker/Dockerfile
    volumes:
      - ./go:/go
      - ./../cloud/gcp/credentials/service_account.json:/go/src/lmm/api/cloud/gcp/credentials/service_account.json
    working_dir: /go/src/lmm/api/
    environment:
      TZ: Asia/Tokyo
      GO111MODULE: 'on'
      HTTP_TIMEOUT_SECOND: 10
    depends_on:
      - datastore
    networks:
      - lmm-api
  datastore:
    image: google/cloud-sdk:247.0.0
    environment:
      TZ: Asia/Tokyo
    networks:
      - lmm-api

networks:
  lmm-api:
    name: lmm-api
