version: "3"
services:
  api:
    env_file:
      - ./.env/test.env
    environment:
      DB_HOST: api-mysql
      DB_PORT: 3306
      DB_NAME: lmm_test
      DB_USER: root
      HTTP_TIMEOUT_SECOND: 1
    working_dir: /go/src/lmm/api
    command: bash -c "go test ./... -count 1 -cover -v"
  mysql:
    volumes:
      - ./mysql/sql/init_test.sql:/mysql/sql/init_test.sql
    command: --init-file /mysql/sql/init_test.sql
