version: "3.7"
services:
  api:
    env_file:
      - ./.env/dev.env
    command: api
    environment:
      APP_HOST: https://www.lmm.local

      MYSQL_PROTOCOL: unix
      MYSQL_ADDR: /var/run/mysqld/mysqld.sock
      MYSQL_DBNAME: lmm
      MYSQL_USER: root
      MYSQL_CONNECTION_RETRY: 3

      RABBIT_HOST: rabbitmq
      RABBIT_PORT: 5672
      RABBIT_USER: guest
      RABBIT_PASS: guest
      REDIS_SERVER: redis:6379
      REDIS_CONN_TIMEOUT_SECOND: 3
      HTTP_TIMEOUT_SECOND: 3
    networks:
      - lmm
  mysql:
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 1

networks:
  lmm:
    external:
      name: lmm
