version: "3.7"
services:
  api:
    image: circleci/golang:1.12.0
    env_file:
      - ./.env/test.env
    environment:
      DATASTORE_EMULATOR_HOST: datastore:8081
      DATASTORE_PROJECT_ID: lmm-test
      GIN_MODE: test
      HTTP_TIMEOUT_SECOND: 3
    working_dir: /go/src/lmm/api
    command: gotestsum -f short-verbose
  datastore:
    environment:
      PROJECT_ID: lmm-test
    command: |
      gcloud beta emulators datastore start --project=lmm-test --host-port=0.0.0.0:8081
