version: "3.7"
services:
  api:
    env_file:
      - ./.env/dev.env
    command: >
      bash -c "sh script/generate_app_yaml.sh &&
      dev_appserver.py app.yaml --host 0.0.0.0 --port 8002 --enable_host_checking=False"
    environment:
      APP_ORIGIN: https://www.lmm.local
      MANAGER_ORIGIN: https://manager.lmm.local
      HTTP_TIMEOUT_SECOND: 3
      DATASTORE_EMULATOR_HOST: datastore:8081
      DATASTORE_PROJECT_ID: lmm-dev
      ASSET_BUCKET_NAME: lmm-dev-asset
      GCP_PROJECT_ID: lmm-dev
      GIN_MODE: debug
      GOOGLE_APPLICATION_CREDENTIALS: /gcp/credentials/service_account.json
    networks:
      - lmm
  datastore:
    volumes:
      - ./.datastore:/root/.config/gcloud/emulators/datastore
    environment:
      PROJECT_ID: lmm
    networks:
      - lmm-api
    command: |
      gcloud beta emulators datastore start --project=lmm-dev --host-port=0.0.0.0:8081

networks:
  lmm:
    external:
      name: lmm
