version: "3"
services:
  api:
    image: lmm/api
    build:
      context: .
    volumes:
      - ../go:/go
      - ../asset:/asset
    working_dir: /go/src/lmm/api
    command: go run cmd/api/main.go
    environment:
      TZ: Asia/Tokyo
      GO111MODULE: 'on'
      HTTP_TIMEOUT_SECOND: 10
    ports:
      - 8002:8002
    links:
      - mysql:api-mysql
      - redis:api-redis
  mysql:
    image: mysql:5.7
    volumes:
      - ./mysql/lib:/var/lib/mysql
      - ./mysql/log:/var/log/mysql
      - ./mysql/my.cnf:/etc/mysql/my.cnf
    environment:
      TZ: Asia/Tokyo
  redis:
    image: redis:5.0-rc
