version: "3.7"
services:
  api:
    container_name: api
    image: golang:1.11
    volumes:
      - ./go:/go
    working_dir: /go/src/lmm/api
    command: go run cmd/api/main.go
    environment:
      TZ: Asia/Tokyo
      GO111MODULE: 'on'
      HTTP_TIMEOUT_SECOND: 10
    networks:
      - api
    ports:
      - 8002:8002
    links:
      - mysql:api-mysql
      - redis:api-redis
  mysql:
    container_name: api_mysql
    image: mysql:5.7
    volumes:
      - ./mysql/lib:/var/lib/mysql
      - ./mysql/log:/var/log/mysql
      - ./mysql/my.cnf:/etc/mysql/my.cnf
      - ./mysql/sql/init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      TZ: Asia/Tokyo
    networks:
      - api
  redis:
    container_name: api_redis
    image: redis:5.0-rc
    networks:
      - api

networks:
  api:
    name: api
