version: "3.7"
services:
  api:
    env_file:
      - ./.env/dev.env
    environment:
      MYSQL_HOST: api-mysql
      MYSQL_PORT: 3306
      MYSQL_NAME: lmm
      MYSQL_USER: root
      RABBIT_HOST: host.docker.internal
      RABBIT_PORT: 5672
      RABBIT_USER: guest
      RABBIT_PASS: guest
      HTTP_TIMEOUT_SECOND: 3
    networks:
      - lmm
  mysql:
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 1

networks:
  lmm:
    external:
      name: lmm
