version: "3.7"
services:
  api:
    env_file:
      - ./.env/dev.env
    command: api
    environment:
      APP_HOST: https://www.lmm.local
      HTTP_TIMEOUT_SECOND: 3
      DATASTORE_EMULATOR_HOST: datastore:8081
      DATASTORE_PROJECT_ID: lmm
      PROJECT_ID: lmm-dev
    networks:
      - lmm
  datastore:
    volumes:
      - ./.datastore:/root/.config/gcloud/emulators/datastore
    environment:
      PROJECT_ID: lmm
    networks:
      - lmm-api
    command: |
      gcloud beta emulators datastore start --project=lmm-test --host-port=0.0.0.0:8081

networks:
  lmm:
    external:
      name: lmm
