version: "3.7"
services:
  api:
    image: golang:1.12.0
    volumes:
      - ./go:/go
      - ./mysql/sql/init.sql:/sql/schema.sql
      - ./../cloud/gcp/credentials/service_account.json:/gcp/credentials/service_account.json
    working_dir: /go/src/lmm/api/
    environment:
      TZ: Asia/Tokyo
      GO111MODULE: 'on'
      HTTP_TIMEOUT_SECOND: 10
    depends_on:
      - datastore
      - mysql
    networks:
      - lmm-api
  mysql:
    image: mysql:5.7.25
    volumes:
      - ./mysql/lib:/var/lib/mysql
      - ./mysql/log:/var/log/mysql
      - ./mysql/my.cnf:/etc/mysql/my.cnf
      - ./mysql/sql/init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      TZ: Asia/Tokyo
    networks:
      - lmm-api
  datastore:
    image: google/cloud-sdk:247.0.0
    environment:
      TZ: Asia/Tokyo
    networks:
      - lmm-api

networks:
  lmm-api:
    name: lmm-api
