version: "3.7"
services:
  api:
    container_name: lmm-api
    image: golang:1.11.2
    volumes:
      - ./go:/go
      - ./../cloud/gcp/credentials/service_account.json:/gcp/credentials/service_account.json
    working_dir: /go/src/lmm/api
    command: go run cmd/api/main.go
    environment:
      TZ: Asia/Tokyo
      GO111MODULE: 'on'
      HTTP_TIMEOUT_SECOND: 10
    ports:
      - 8002:8002
  mysql:
    container_name: lmm-api-mysql
    image: mysql:5.7
    volumes:
      - ./mysql/lib:/var/lib/mysql
      - ./mysql/log:/var/log/mysql
      - ./mysql/my.cnf:/etc/mysql/my.cnf
      - ./mysql/sql/init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      TZ: Asia/Tokyo
