on:
  push:
    branches:
      - develop
jobs:
  create-pr:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: develop
      - run: |
          branch="feature/deploy-to-release-environment-$(date '+%Y%m%d%H%M%S')"
          git checkout -b $branch
          hub pull-request --base=release --head=$branch
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
