on:
  push:
    branches:
      - master
jobs:
  create-pr:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: master
      - run: |
          branch="feature/deploy-to-develop-environment-$(date '+%Y%m%d%H%M%S')"
          git checkout -b $branch
          hub pull-request --base=develop --head=$branch
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
